// Update the celebrityAchievements object with real achievements
const celebrityAchievements = {
  rogerfederer: {
    "grand-slams": [
      {
        id: 1,
        title: "Wimbledon Championships",
        count: "8x Winner",
        years: "2003, 2004, 2005, 2006, 2007, 2009, 2012, 2017",
        icon: "🎾",
        description: "Record holder for most Wimbledon men's singles titles in the Open Era",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 2,
        title: "Australian Open",
        count: "6x Winner",
        years: "2004, 2006, 2007, 2010, 2017, 2018",
        icon: "🏆",
        description: "Six-time champion at Melbourne Park",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 3,
        title: "US Open",
        count: "5x Winner",
        years: "2004, 2005, 2006, 2007, 2008",
        icon: "🗽",
        description: "Five consecutive titles at Flushing Meadows",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 4,
        title: "French Open",
        count: "1x Winner",
        years: "2009",
        icon: "🇫🇷",
        description: "Completed Career Grand Slam with victory at Roland Garros",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    masters: [
      {
        id: 5,
        title: "ATP Finals",
        count: "6x Winner",
        years: "2003, 2004, 2006, 2007, 2010, 2011",
        icon: "👑",
        description: "Record-tying six titles at year-end championships",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 6,
        title: "Cincinnati Masters",
        count: "7x Winner",
        years: "2005, 2007, 2009, 2010, 2012, 2014, 2015",
        icon: "🏅",
        description: "Most titles at Cincinnati Masters in the Open Era",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 7,
        title: "Basel",
        count: "10x Winner",
        years: "2006-2019",
        icon: "🇨🇭",
        description: "Ten titles at his hometown tournament",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    olympics: [
      {
        id: 8,
        title: "Olympic Gold Medal",
        count: "1x Winner",
        years: "2008",
        icon: "🥇",
        description: "Men's Doubles Gold Medal with Stan Wawrinka at Beijing Olympics",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 9,
        title: "Olympic Silver Medal",
        count: "1x Winner",
        years: "2012",
        icon: "🥈",
        description: "Men's Singles Silver Medal at London Olympics",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    rankings: [
      {
        id: 10,
        title: "World No. 1",
        count: "310 Weeks",
        years: "2004-2018",
        icon: "📊",
        description: "Record for most weeks ranked as World No. 1 (since broken by Djokovic)",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 11,
        title: "Year-End No. 1",
        count: "5x Achievement",
        years: "2004, 2005, 2006, 2007, 2009",
        icon: "🌟",
        description: "Finished five years as World No. 1",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
  },
  kendricklamar: {
    grammys: [
      {
        id: 1,
        title: "Best Rap Album",
        count: "3x Winner",
        years: "2015, 2016, 2018",
        icon: "🏆",
        description: "Grammy Awards for 'To Pimp a Butterfly', 'DAMN.', and 'Mr. Morale & the Big Steppers'",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 2,
        title: "Best Rap Performance",
        count: "6x Winner",
        years: "2015-2023",
        icon: "🎤",
        description: "Multiple wins including 'i', 'HUMBLE.', and 'The Heart Part 5'",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 3,
        title: "Best Music Video",
        count: "1x Winner",
        years: "2015",
        icon: "🎬",
        description: "Grammy Award for 'HUMBLE.'",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    "other-awards": [
      {
        id: 4,
        title: "Pulitzer Prize",
        count: "1x Winner",
        years: "2018",
        icon: "📜",
        description: "First non-classical or jazz artist to win the Pulitzer Prize for Music (DAMN.)",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 5,
        title: "BET Awards",
        count: "12x Winner",
        years: "2013-2023",
        icon: "🎭",
        description: "Multiple wins including Album of the Year and Lyricist of the Year",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 6,
        title: "NAACP Image Awards",
        count: "6x Winner",
        years: "2014-2023",
        icon: "🏅",
        description: "Outstanding Male Artist and Album awards",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    albums: [
      {
        id: 7,
        title: "DAMN.",
        count: "Triple Platinum",
        years: "2017",
        icon: "💿",
        description: "Pulitzer Prize-winning album, 3 million+ sales",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 8,
        title: "To Pimp a Butterfly",
        count: "Platinum",
        years: "2015",
        icon: "🦋",
        description: "Widely regarded as one of the greatest albums of all time",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 9,
        title: "good kid, m.A.A.d city",
        count: "Triple Platinum",
        years: "2012",
        icon: "📀",
        description: "Longest-charting hip-hop studio album on Billboard 200",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    cultural: [
      {
        id: 10,
        title: "Time 100",
        count: "2x Listed",
        years: "2016, 2019",
        icon: "⭐",
        description: "Named one of Time's 100 most influential people",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 11,
        title: "California Senate Honor",
        count: "Generational Icon",
        years: "2015",
        icon: "🏛️",
        description: "Honored as 'Generational Icon' by California State Senate",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
  },
  michelleobama: {
    books: [
      {
        id: 1,
        title: "Becoming",
        count: "17M+ Copies",
        years: "2018",
        icon: "📚",
        description: "Best-selling memoir of all time by a First Lady, translated into 31 languages",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 2,
        title: "The Light We Carry",
        count: "#1 Bestseller",
        years: "2022",
        icon: "📖",
        description: "New York Times Bestseller, offering wisdom for uncertain times",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 3,
        title: "American Grown",
        count: "Bestseller",
        years: "2012",
        icon: "🌱",
        description: "Book about the White House Kitchen Garden and gardens across America",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    initiatives: [
      {
        id: 4,
        title: "Let's Move!",
        count: "National Impact",
        years: "2010-2016",
        icon: "🏃‍♀️",
        description: "Campaign against childhood obesity, reaching millions of children",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 5,
        title: "Reach Higher",
        count: "Ongoing",
        years: "2014-Present",
        icon: "🎓",
        description: "Initiative to inspire young people to complete education beyond high school",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 6,
        title: "Girls Opportunity Alliance",
        count: "Global Impact",
        years: "2018-Present",
        icon: "🌍",
        description: "Program empowering adolescent girls through education worldwide",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    awards: [
      {
        id: 7,
        title: "Grammy Award",
        count: "1x Winner",
        years: "2020",
        icon: "🎵",
        description: "Best Spoken Word Album for 'Becoming' audiobook",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 8,
        title: "People of the Year",
        count: "Multiple Times",
        years: "2008-2019",
        icon: "🌟",
        description: "Named among Time's and People's most influential people",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
    education: [
      {
        id: 9,
        title: "Princeton University",
        count: "Bachelor's",
        years: "1985",
        icon: "🎓",
        description: "Bachelor's degree in Sociology and African American Studies",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 10,
        title: "Harvard Law School",
        count: "J.D.",
        years: "1988",
        icon: "⚖️",
        description: "Juris Doctor degree from Harvard Law School",
        image: "/placeholder.svg?height=300&width=400",
      },
      {
        id: 11,
        title: "Honorary Degrees",
        count: "10+ Degrees",
        years: "2009-Present",
        icon: "🎓",
        description: "Honorary degrees from multiple prestigious universities",
        image: "/placeholder.svg?height=300&width=400",
      },
    ],
  },
}

